repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
    -   id: ruff
        args: [--fix]
        files: ^backend/
    -   id: ruff-format
        files: ^backend/

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    -   id: mypy
        additional_dependencies: 
          - types-python-jose
          - types-passlib
          - types-python-dateutil
          - sqlalchemy
          # - sqlalchemy-stubs
        args: 
          - --ignore-missing-imports
          - --disallow-untyped-defs
          - --disallow-incomplete-defs
          - --check-untyped-defs
          - --no-warn-return-any
          - --warn-redundant-casts
          - --warn-unused-ignores
          - --warn-no-return
          - --warn-unreachable
        files: ^backend/ 