[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
    "N",  # pep8-naming
    "PL", # pylint
    "RUF",# ruff-specific
]
ignore = [
    "E501",  # line too long (handled by black)
    "PLR2004", # magic value used in comparison
    "B008",  # function call in argument defaults (common in FastAPI with Depends)
    "E712",
]

[tool.ruff.lint.isort]
known-first-party = ["app"]

[tool.mypy]
python_version = "3.12"
# Removed SQLAlchemy plugin as it's causing compatibility issues
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_optional = true
follow_imports = "silent"
no_implicit_reexport = true

[[tool.mypy.overrides]]
module = [
    "alembic.*",
    "sqlalchemy.*",
]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["*.tests.*"]
disallow_untyped_defs = false 